# use Ganache's forked mainnet mode as the default network
networks:
  default: SamLocal-Fork
  SamLocal-Fork:
    cmd_settings:
      unlock:
        - 0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8
        - 0xC3D6880fD95E06C816cB030fAc45b3ffe3651Cb0
        - 0xf2d373481e1da4a8ca4734b28f5a642d55fda7d3
        - 0x767Ecb395def19Ab8d1b2FCc89B3DDfBeD28fD6b
      #fork: 'http://127.0.0.1:9999@11168031'

  
# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.12
    remappings:
      - "@openzeppelinV3=OpenZeppelin/openzeppelin-contracts@3.1.0"
      #- "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
      #- "@yearnvaultsV2=iearn-finance/yearn-vaults@0.1.1"

reports:
  exclude_paths:
    - contracts/test/Token.sol
